name: roopkatha
description: "A new Flutter project."

publish_to: 'none' # Keep private

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http:
  get:
  get_storage:
  google_fonts:
  intl: 0.18.0 # Downgrade intl for Khalti
  flutter_svg: ^2.0.17
  shared_preferences:
  flutter_secure_storage:
  table_calendar:
  khalti_flutter: ^3.0.0
  khalti:
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.8
  url_launcher: ^6.0.3

dependency_overrides:
  intl: 0.18.0 # Force intl 0.18.0 to resolve conflicts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/welcome.png
    - assets/khalti_logo.png
